version: '3.7'

services:
    db:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: hotels


    nginx:
      image: nginx:latest
      volumes:
        - ./public:/app
        - ./site.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "3000:80"
      depends_on:
        - php



    php:
      build:
        context: .
        dockerfile: Dockerfile
#      image: php:7.4-fpm
      volumes:
        - ./:/app
      depends_on:
        - db


    adminer:
      image: adminer
      restart: always
      ports:
        - 8080:8080



